#  Deploy terraform
#  STATUS: INCOMPLETE
#

trigger:
  - solution/bt-2021.06

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'PayG-sp-conn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'terraform init -input=false'
      workingDirectory: '.deploy/azure'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'PayG-sp-conn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'terraform plan -out=tfplan -input=false -var=resourceGroupName="$(resourceGroupName)"'
      workingDirectory: '.deploy/azure'
# Task - deploy infra

# Task - Run DB seed task with container image.
